version: 2
jobs:
  build:
    docker:
      - image: suculent/platformio-docker-build

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install cmake
      - run:
          name: SimpleModule Test
          command: cmake . && make && ./TestSimpleModule
